// <auto-generated />
namespace TaskManagement.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Drop_Parent_Option_String : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Drop_Parent_Option_String));
        
        string IMigrationMetadata.Id
        {
            get { return "202303011404533_Drop_Parent_Option_String"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
